      // File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMfNfkoOaRvwOxPvhsUyNirTmvdIHp64c',
    appId: '1:313962503232:android:3ea4d6e81f6c53a3e693a5',
    messagingSenderId: '313962503232',
    projectId: 'spotify-78b1f',
    storageBucket: 'spotify-78b1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMb26zIqSmEhB-4ZjdMCk6J2P2RVbE2Sc',
    appId: '1:313962503232:ios:104f3cb8503dc083e693a5',
    messagingSenderId: '313962503232',
    projectId: 'spotify-78b1f',
    storageBucket: 'spotify-78b1f.firebasestorage.app',
    iosClientId: '313962503232-cjgrg8pnpksmjq0i9ta8cgc1i74m3rlb.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsZYA1r8NaECVGXpCxljJatxYByEfDOBo',
    appId: '1:313962503232:web:86890fcd22d30b4fe693a5',
    messagingSenderId: '313962503232',
    projectId: 'spotify-78b1f',
    authDomain: 'spotify-78b1f.firebaseapp.com',
    storageBucket: 'spotify-78b1f.firebasestorage.app',
    measurementId: 'G-VM5NVYY416',
  );

}